import { Outfit } from "next/font/google";
import Navber from "@/components/Navber";
import Footer from "@/components/Footer";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`h-full antialiased`}
    >
      <body className={`${outfit.className} min-h-full flex flex-col`}>
        <Navber />
        <main className="">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
